// alert("Lets Go!!!")


// let ans = confirm("are you sure?")

// == != > < >= <=  |-> === !==

// console.log(12>=12)
// console.log(12<=12)
// console.log(12>12)
// console.log(12<12)


let a =12;
let b ='12';

// console.log(a==b)
// console.log(a===b)
// console.log(a!==b)

//Type Casting
// console.log(a+Number(b))
// console.log(a+parseInt(b))

// let message = "12345g3246";
// console.log(Number(message))
// console.log(parseInt(message))


// console.log(Boolean("true") == true)

// console.log(String(a))
// console.log(a.toString())

//[]{}


// && || !

// True && True - > True
// True && False - > False
// False && True - > False
// False && False - > False

// True || True - > True
// True || False - > True
// False || True - > True
// False || False - > False

// !True -> False
// !False -> True

//! && ||

// console.log(!(true||!false&&true))

// () {} [] 
// '' "" ``



// if(true){
    //     console.log("True Block")
    // }else{
        //     console.log("False Block")
        // }
        
        
        
        
// if(true){
//     console.log("True Block")
//     if(false){
//         console.log("Hello")
//     }else{
//         console.log("Hii")
//     }
// }else{
//     console.log("False Block")
// }


// if(false){

// }else if(false){

// }else if(false){

// }else{
//     console.log("............")
// }



// switch(3){
//     case 1:
//         console.log("Hello From Case 1")
//     break
//     case 2:
//         console.log("Hello From Case 2")
//         break
//     case 3:
//         console.log("Hello From Case 3")
//         break
//     default:
//         console.log("Default Case")
//         break
// }








